spring:
  application:
    name: soil

startup:
  logger:
    enabled: true
    time-unit: ms

logging:
  level:
    org.springframework.boot.autoconfigure.logging: debug

condition:
  or:
    enable: "false"
    use: "yes"